const RAW_BADGES="https://raw.githubusercontent.com/Fmasterpro27/Discord-badges/main/assets";
const MAX_VERSTAPPEN_LOGO="/images/max-verstappen.png";
const MONACO_TRACK="/images/monaco.png";
const FERRARI_LOGO="/images/ferrari.png";
const F1_TRACKS={"Dutch Grand Prix":"https://upload.wikimedia.org/wikipedia/commons/4/4a/Zandvoort.svg","Italian Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Monza.svg","Azerbaijan Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Baku.svg","Singapore Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Marina_Bay_Street_Circuit.svg","Japanese Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Suzuka_circuit_map.svg","British Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Silverstone_Circuit.svg","Belgian Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Circuit_Spa-Francorchamps.svg","Hungarian Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Hungaroring.svg","Austrian Grand Prix":"https://commons.wikimedia.org/wiki/Special:FilePath/Red_Bull_Ring.svg","Monaco Grand Prix":MONACO_TRACK};
function addStyles(){if(document.getElementById("draven-enhancement-styles"))return;const s=document.createElement("style");s.id="draven-enhancement-styles";s.textContent=`
.badges.actual-badges{display:flex;align-items:center;gap:6px;margin-top:6px}.actual-badge{width:15px;height:15px;object-fit:contain;display:block;filter:drop-shadow(0 2px 5px #0008)}
.recent-card.song-link{cursor:pointer}.recent-card.song-link:hover strong,.np-song-link:hover strong{color:#fff}.placeholder-art{width:100%;height:100%;object-fit:cover;border-radius:50%;background:#15151a}
.recent-scroller .recent-card{width:142px;min-width:142px;height:166px;border-radius:0;position:relative;overflow:visible;padding:0;background:transparent;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;box-shadow:none}
.recent-scroller .recent-card>img{position:relative;inset:auto;width:124px;height:124px;flex:0 0 124px;object-fit:cover;border-radius:50%;opacity:.92;box-shadow:0 12px 30px #000b,0 0 20px #ffffff12;outline:1px solid #303038;z-index:1}
.recent-scroller .recent-card>div{position:relative;z-index:4;width:100%;box-sizing:border-box;padding:7px 4px 0;background:none;display:block;text-align:center}
.recent-scroller .recent-card:after{content:"";position:absolute;z-index:3;width:16px;height:16px;left:50%;top:54px;transform:translate(-50%,-50%);border-radius:50%;background:#0b0b0e;border:2px solid #686870;box-shadow:0 0 0 4px #151519,0 2px 8px #000b;pointer-events:none}
.recent-scroller .recent-card strong{font-size:9px;display:block;white-space:nowrap;overflow:visible;text-overflow:clip;max-width:100%;line-height:1.25}.recent-scroller .recent-card small{font-size:8px;display:block;white-space:nowrap;overflow:visible;text-overflow:clip;max-width:100%;line-height:1.25;color:#9999a2}.recent-scroller .now-dot{z-index:5;right:13px!important;top:7px!important}
.f1-hero{background:linear-gradient(145deg,#101014,#0b0b0e)!important;box-shadow:0 24px 70px #0008!important}.f1-mark{color:#9a9aa2!important}.f1-logo{color:#aaa!important;opacity:.08!important}.interest{background:#0d0d10!important;border-color:#24242a!important}.f1-points,.next-race{background:#0d0d10!important;border-color:#24242a!important}.f1-points .bar{background:#1b1b20!important}.f1-points .bar span{background:#777!important}.f1-asset{width:42px;height:42px;object-fit:contain;display:block}.driver-number-logo{width:48px;height:48px;object-fit:contain;display:block;filter:drop-shadow(0 2px 8px #0008)}.track-preview{width:56px;height:46px;object-fit:contain;filter:invert(1) brightness(.78) contrast(1.2);opacity:.95}.f1-interest-grid .interest>span:has(.f1-asset),.f1-interest-grid .interest>span:has(.track-preview),.f1-interest-grid .interest>span:has(.driver-number-logo){width:52px;height:46px;background:transparent}.f1-interest-grid .interest[data-hidden-merch="1"]{display:none}
.f1-interest-grid .interest>span:has(.f1-asset),.f1-interest-grid .interest>span:has(.driver-number-logo){border:0!important;outline:0!important;box-shadow:none!important;background:transparent!important}.f1-interest-grid .interest>span:has(.f1-asset) img,.f1-interest-grid .interest>span:has(.driver-number-logo) img{border:0!important;outline:0!important;box-shadow:none!important}
.adobe-real-icon{width:15px;height:15px;object-fit:contain;vertical-align:-3px;margin-right:4px}.artist-real-icon{width:34px!important;height:34px!important;border-radius:50%!important;object-fit:cover!important;display:block!important;flex:0 0 34px}.music-item .artist-real-icon{box-shadow:0 3px 10px #0008}
@media(max-width:700px){body{cursor:auto!important}.cursor-dot,.star-trail{display:none!important}.recent-scroller .recent-card{width:122px;min-width:122px;height:148px}.recent-scroller .recent-card>img{width:108px;height:108px;flex-basis:108px}.recent-scroller .recent-card:after{top:47px}}
`;document.head.appendChild(s)}
function decorateDiscord(){const info=document.querySelector(".discord-info");if(!info)return;const source=info.querySelector(".badges");if(source)[...source.querySelectorAll("span")].forEach(el=>{const t=(el.title||"").toLowerCase(),v=el.textContent.trim();if(t.includes("hypesquad bravery")||v==="BRV")el.remove()});let box=info.querySelector(".badges.actual-badges");if(!box){box=document.createElement("div");box.className="badges actual-badges";info.appendChild(box)}if(box.dataset.actualBadges)return;box.dataset.actualBadges="1";box.innerHTML="";[[RAW_BADGES+"/profile_badges/discordnitro.svg","Discord Nitro badge"],[RAW_BADGES+"/nitro_booster/discordboost1.svg","Server Booster badge"]].forEach(([src,title])=>{const img=document.createElement("img");img.className="actual-badge";img.src=src;img.alt=title;img.title=title;box.appendChild(img)})}
function flipDigits(){document.querySelectorAll(".flip").forEach(el=>{if(el.dataset.flipBusy==="1")return;const value=el.textContent;if(el.dataset.lastValue===undefined){el.dataset.lastValue=value;return}if(el.dataset.lastValue===value)return;const old=el.dataset.lastValue;el.dataset.lastValue=value;el.dataset.flipBusy="1";el.textContent=old;el.__flipA?.cancel();el.__flipB?.cancel();el.__flipA=el.animate([{transform:"perspective(180px) rotateX(0deg)"},{transform:"perspective(180px) rotateX(-90deg)"}],{duration:260,easing:"ease-in",fill:"forwards"});setTimeout(()=>{if(el.dataset.flipBusy!=="1")return;el.textContent=value;el.__flipB=el.animate([{transform:"perspective(180px) rotateX(90deg)"},{transform:"perspective(180px) rotateX(0deg)"}],{duration:260,easing:"ease-out",fill:"forwards"});el.__flipB.finished.catch(()=>{}).finally(()=>{el.dataset.flipBusy="0";el.style.transform=""})},260)})}
function normalizeTimezone(){document.querySelectorAll(".clock-meta small").forEach(el=>{if(el.textContent!=="UTC+7")el.textContent="UTC+7"})}
function lastfmUrl(a,t){return a&&t?`https://www.last.fm/music/${encodeURIComponent(a)}/_/${encodeURIComponent(t)}`:""}
function placeholderSvg(){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96"><rect width="96" height="96" rx="48" fill="#15151a"/><circle cx="48" cy="48" r="25" fill="none" stroke="#777780" stroke-width="4"/><circle cx="48" cy="48" r="7" fill="#777780"/><path d="M39 33v30l24-15z" fill="#777780"/></svg>`)}
function linkMusic(){const ph=placeholderSvg();document.querySelectorAll(".recent-card").forEach(card=>{if(card.classList.contains("skeleton-recent"))return;let img=card.querySelector("img");if(!img||!img.getAttribute("src")){if(!img){img=document.createElement("img");img.alt="";card.insertBefore(img,card.firstChild)}img.src=ph;img.className="placeholder-art"}if(img.dataset.fallbackBound!=="1"){img.dataset.fallbackBound="1";img.addEventListener("error",()=>{if(img.src!==ph)img.src=ph})}const t=card.querySelector("strong")?.textContent?.trim(),a=card.querySelector("small")?.textContent?.trim(),u=lastfmUrl(a,t);if(!u||card.dataset.linked)return;card.dataset.linked="1";card.classList.add("song-link");card.title="Open on Last.fm";card.onclick=()=>window.open(u,"_blank","noopener,noreferrer")});const np=document.querySelector(".np-bottom");if(np){np.querySelector("button")?.remove();const t=np.querySelector("strong")?.textContent?.trim(),a=np.querySelector("small")?.textContent?.split(" · ")[0]?.trim(),u=lastfmUrl(a,t);if(u&&!np.dataset.linked){np.dataset.linked="1";const text=np.querySelector("div");if(text){text.classList.add("np-song-link");text.style.cursor="pointer";text.onclick=()=>window.open(u,"_blank","noopener,noreferrer")}}}}
function firstImage(entry){const list=Array.isArray(entry?.image)?entry.image:[];for(let i=list.length-1;i>=0;i--){const v=list[i]?.["#text"];if(typeof v==="string"&&v.trim())return v.trim()}return ""}
async function hydrateArtistImages(){if(document.body.dataset.artistHydrated==="1")return;document.body.dataset.artistHydrated="1";try{const r=await fetch("/api/lastfm?type=artists");const data=await r.json();const artists=data?.topartists?.artist||[];const map=new Map(artists.map(a=>[String(a.name||"").toLowerCase(),firstImage(a)]));document.querySelectorAll(".music-item").forEach(item=>{const name=item.querySelector("strong")?.textContent?.trim(),url=map.get(String(name||"").toLowerCase());if(!name||!url)return;let old=item.querySelector("img");if(!old){old=document.createElement("img");item.insertBefore(old,item.querySelector("div"))}old.src=url;old.alt=name;old.className="artist-real-icon";old.style.display="block"})}catch{}}
function iconSvg(type){const text=type==='After Effects'?'Ae':type==='Photoshop'?'Ps':'Me';return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="1" fill="#999999"/><text x="12" y="15.2" text-anchor="middle" font-family="Arial,sans-serif" font-size="10" font-weight="700" fill="#1b1b20">${text}</text></svg>`)}`}
function decorateSkills(){document.querySelectorAll(".skill-group .pill").forEach(p=>{const raw=[...p.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent.trim()).filter(Boolean).join(" ").trim();const key=raw==='After Effects'?'After Effects':raw==='Photoshop'?'Photoshop':raw==='Adobe Media Encoder'?'Media Encoder':null;if(!key||p.dataset.adobeDone)return;p.dataset.adobeDone="1";p.querySelector("img")?.remove();p.querySelector("svg")?.remove();const img=document.createElement("img");img.src=iconSvg(key);img.className="adobe-real-icon";img.alt=key;p.prepend(img)})}
function decorateF1(){const i=document.querySelectorAll(".f1-interest-grid .interest");if(i.length<2)return;const c=i[0],d=i[1];if(!c.dataset.asset){c.dataset.asset="1";const s=c.querySelector(":scope > span");if(s){s.innerHTML="";const img=document.createElement("img");img.className="f1-asset";img.src=FERRARI_LOGO;img.alt="Scuderia Ferrari HP";s.appendChild(img)}}if(!d.dataset.asset){d.dataset.asset="1";const s=d.querySelector(":scope > span");if(s){s.innerHTML="";const img=document.createElement("img");img.className="driver-number-logo";img.src=MAX_VERSTAPPEN_LOGO;img.alt="Max Verstappen";img.title="Max Verstappen";s.appendChild(img)}}if(i.length>2){for(let n=2;n<i.length;n++){i[n].style.display="none";i[n].dataset.hiddenF1="1"}}}
function fixVerstappenImage(){document.querySelectorAll(".interest-image").forEach(img=>{if(img.alt?.toLowerCase().includes("max verstappen")||img.src.includes("seeklogo")||img.src.includes("liquipedia.net")){img.src=MAX_VERSTAPPEN_LOGO;img.alt="Max Verstappen"}})}
function fixFerrariImage(){document.querySelectorAll(".interest-image").forEach(img=>{const alt=(img.alt||"").toLowerCase(),src=(img.src||"").toLowerCase();if(alt.includes("scuderia ferrari")||alt.includes("ferrari")||src.includes("scuderia-logo-v02")||src.includes("ferrarioffortlauderdale")){img.src=FERRARI_LOGO;img.alt="Scuderia Ferrari"}})}
function run(){addStyles();decorateDiscord();flipDigits();normalizeTimezone();linkMusic();decorateSkills();decorateF1();fixVerstappenImage();fixFerrariImage();hydrateArtistImages()}
const root=document.getElementById("root")||document.body;const observer=new MutationObserver(run);observer.observe(root,{childList:true,subtree:true,characterData:true});run();
