const F1_SCHEDULE_API="https://api.jolpi.ca/f1/2026.json";
const F1_SESSION_LABELS={FP1:"Practice 1",FP2:"Practice 2",FP3:"Practice 3",SQ:"Sprint Qualifying",SR:"Sprint Race",Q:"Qualifying",R:"Grand Prix"};
const F1_SESSION_ORDER={FP1:1,SQ:2,SR:3,FP2:4,FP3:5,Q:6,R:7};
const FALLBACK_DUTCH_SCHEDULE=[{key:"fp1",name:"Practice 1",iso:"2026-08-21T09:30:00Z"},{key:"sq",name:"Sprint Qualifying",iso:"2026-08-21T13:30:00Z"},{key:"sr",name:"Sprint Race",iso:"2026-08-22T09:00:00Z"},{key:"q",name:"Qualifying",iso:"2026-08-22T13:00:00Z"},{key:"r",name:"Grand Prix",iso:"2026-08-23T13:00:00Z"}];
function formatCountdown(ms){if(ms<=0)return "LIVE / COMPLETED";const total=Math.floor(ms/1000),d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),s=total%60;return `${d}d ${String(h).padStart(2,"0")}h ${String(m).padStart(2,"0")}m ${String(s).padStart(2,"0")}s`}
function sessionTimestamp(iso){const d=new Date(iso);if(Number.isNaN(d.getTime()))return "";return `${new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jakarta",hour12:false}).format(d)} WIB`}
function parseSessionDate(value){if(!value)return null;if(typeof value==="string")return new Date(value).getTime();if(typeof value!=="object")return null;const date=value.date||value.Date,time=value.time||value.Time||"00:00:00Z";if(date)return new Date(`${date}T${time.replace(/Z$/i,"")}Z`).getTime();return null}
function buildRaceRows(race){const candidates=[];const add=(code,value)=>{const t=parseSessionDate(value);if(Number.isFinite(t))candidates.push({key:code.toLowerCase(),name:F1_SESSION_LABELS[code],iso:new Date(t).toISOString()})};add("FP1",race.FirstPractice);add("SQ",race.SprintQualifying||race.SprintShootout);add("SR",race.Sprint);add("FP2",race.SecondPractice);add("FP3",race.ThirdPractice);add("Q",race.Qualifying);if(race.date)add("R",{date:race.date,time:race.time||"00:00:00Z"});return candidates.sort((a,b)=>new Date(a.iso)-new Date(b.iso))}
function raceTitle(race){return race?.raceName||race?.name||"Grand Prix"}
function raceLocation(race){return race?.Circuit?.Location?.locality&&race?.Circuit?.Location?.country?`${race.Circuit.Location.locality}, ${race.Circuit.Location.country}`:race?.Circuit?.circuitName||""}
let f1ScheduleCache=null,f1SchedulePromise=null;
async function loadF1Schedule(){if(f1ScheduleCache)return f1ScheduleCache;if(f1SchedulePromise)return f1SchedulePromise;f1SchedulePromise=fetch(F1_SCHEDULE_API,{cache:"no-store",headers:{Accept:"application/json"}}).then(r=>{if(!r.ok)throw Error("F1 schedule request failed");return r.json()}).then(data=>{const races=data?.MRData?.RaceTable?.Races||[];const now=Date.now()-12*60*60*1000;const candidates=races.map(race=>({race,rows:buildRaceRows(race)})).filter(x=>x.rows.some(r=>new Date(r.iso).getTime()>now));candidates.sort((a,b)=>new Date(a.race.date||a.rows[0]?.iso)-new Date(b.race.date||b.rows[0]?.iso));if(!candidates.length)throw Error("No upcoming F1 schedule found");const selected=candidates[0];f1ScheduleCache={title:raceTitle(selected.race),location:raceLocation(selected.race),rows:selected.rows};return f1ScheduleCache}).catch(()=>null).finally(()=>{f1SchedulePromise=null});return f1SchedulePromise}
function ensureScheduleHost(){const box=document.querySelector(".next-race"),host=box?.querySelector(".countdown");if(!host)return null;if(!host.shadowRoot)host.attachShadow({mode:"open"});return host.shadowRoot}
function renderScheduleData(data){const root=ensureScheduleHost();if(!root||!data?.rows?.length)return;root.innerHTML=`<style>:host{display:block;width:100%;height:100%}.wrap{display:flex;flex-direction:column;gap:7px;min-width:210px}.head{font-size:8px;color:#777;letter-spacing:.08em;text-transform:uppercase;margin-bottom:2px}.session{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:7px 8px;border:1px solid #24242a;border-radius:8px;background:#111116;transition:border-color .18s ease,background .18s ease}.session:hover{border-color:#3a3a42;background:#14141a}.info b{display:block;font-size:8px;color:#eee;text-transform:uppercase;letter-spacing:.04em}.info small{display:block;margin-top:3px;color:#8f8f98;font-size:7px}.count{font-size:8px;font-weight:700;white-space:nowrap;text-align:right;color:#ddd}.done{opacity:.58}.done .count{color:#777}.title{font-size:10px;font-weight:700;color:#aaa;margin-bottom:1px}.location{font-size:7px;color:#777;margin-bottom:3px}@media(max-width:700px){.wrap{min-width:0}.session{align-items:flex-start;flex-direction:column;gap:4px}.count{text-align:left}}</style><div class="wrap"><div class="title">${data.title||"Next Grand Prix"}</div><div class="location">${data.location||""}</div><div class="sessions"></div></div>`;const list=root.querySelector(".sessions");data.rows.forEach(row=>{const el=document.createElement("div");el.className="session";el.innerHTML=`<div class="info"><b>${row.name}</b><small>${sessionTimestamp(row.iso)}</small></div><div class="count"></div>`;list.appendChild(el);const count=el.querySelector(".count"),time=new Date(row.iso).getTime();const tick=()=>{const left=time-Date.now();count.textContent=formatCountdown(left);el.classList.toggle("done",left<=0)};tick();const id=setInterval(tick,1000);el.dataset.timer=String(id)})}
function renderFallback(){renderScheduleData({title:"Dutch Grand Prix",location:"Zandvoort, Netherlands",rows:FALLBACK_DUTCH_SCHEDULE})}
async function renderF1Schedule(){const data=await loadF1Schedule();if(data){renderScheduleData(data);return}renderFallback()}
async function updateF1SeasonCompletion(){const bar=document.querySelector(".f1-points .bar");if(!bar||bar.dataset.seasonCompletionBound==="1")return;bar.dataset.seasonCompletionBound="1";const update=async()=>{try{const response=await fetch(F1_SCHEDULE_API,{cache:"no-store",headers:{Accept:"application/json"}});if(!response.ok)throw Error("F1 calendar request failed");const data=await response.json(),races=data?.MRData?.RaceTable?.Races||[];if(!races.length)throw Error("No F1 races found");const now=Date.now(),total=races.length,completed=races.filter(r=>{const t=parseSessionDate({date:r.date,time:r.time||"00:00:00Z"});return Number.isFinite(t)&&t<=now}).length,percentage=Math.max(0,Math.min(100,completed/total*100)),fill=bar.querySelector(":scope > span:first-child");if(fill)fill.style.width=`${percentage.toFixed(1)}%`;bar.dataset.seasonCompletion=percentage.toFixed(1)}catch{}};await update();setInterval(update,15*60*1000)}
let scheduleRenderTimer=null;
function bootF1Schedule(){const root=document.getElementById("root")||document.body;const observer=new MutationObserver(()=>{updateF1SeasonCompletion();if(document.querySelector(".next-race .countdown")&&!document.querySelector(".next-race .countdown")?.shadowRoot){clearTimeout(scheduleRenderTimer);scheduleRenderTimer=setTimeout(renderF1Schedule,50)}});observer.observe(root,{childList:true,subtree:true});renderF1Schedule();updateF1SeasonCompletion();setInterval(()=>{f1ScheduleCache=null;renderF1Schedule()},15*60*1000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootF1Schedule);else bootF1Schedule();
