// Clean rebuild of the music artwork integration for the current React Music page.
const MUSIC_ART_STYLE_ID="music-artwork-rebuild";
function addMusicArtworkStyles(){if(document.getElementById(MUSIC_ART_STYLE_ID))return;const s=document.createElement("style");s.id=MUSIC_ART_STYLE_ID;s.textContent=`#music .music-list .music-item{cursor:pointer}#music .music-list .music-item:hover strong{color:#fff}#music .music-list:first-child .music-item{grid-template-columns:16px minmax(0,1fr)!important}#music .music-list:first-child .music-item strong{white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;overflow-wrap:normal!important;min-width:0!important}#music .music-list:last-child .music-item{grid-template-columns:16px 48px minmax(0,1fr)!important}#music .music-list:last-child .music-item>img.music-album-art{width:48px!important;height:48px!important;border-radius:6px!important;object-fit:cover!important;display:block!important;flex:none!important}#music .record-disc{background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important}@media(max-width:700px){#music .music-list:first-child .music-item{grid-template-columns:16px minmax(0,1fr)!important}#music .music-list:last-child .music-item{grid-template-columns:16px 42px minmax(0,1fr)!important}#music .music-list:last-child .music-item>img.music-album-art{width:42px!important;height:42px!important}}`;document.head.appendChild(s)}
function bestImage(e){const a=e?.image;if(Array.isArray(a)){for(let i=a.length-1;i>=0;i--){const v=a[i]?.["#text"];if(typeof v==="string"&&v.trim()&&v!=="https://lastfm.freetls.fastly.net/i/u/34s/undefined")return v.trim()}}if(a&&typeof a==="object"){for(const k of ["extralarge","large","medium","small"]){const v=a[k]?.["#text"]??a[k];if(typeof v==="string"&&v.trim())return v.trim()}}return ""}
async function lastFm(type){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(`/api/lastfm?type=${type}`,{signal:c.signal,cache:"no-store"});if(!r.ok)throw Error(`${type} failed`);return await r.json()}finally{clearTimeout(t)}}
function artistUrl(n){return `https://www.last.fm/music/${encodeURIComponent(n).replace(/%20/g,"+")}`}
function albumUrl(a,n){return `https://www.last.fm/music/${encodeURIComponent(a).replace(/%20/g,"+")}/${encodeURIComponent(n).replace(/%20/g,"+")}`}
function linkItem(item,url){if(!item||!url||item.dataset.lastfmLinked)return;item.dataset.lastfmLinked="1";item.tabIndex=0;item.addEventListener("click",()=>window.open(url,"_blank","noopener,noreferrer"));item.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();window.open(url,"_blank","noopener,noreferrer")}})}
function lists(){return [...document.querySelectorAll("#music .music-list")]}
async function rebuildMusic(){const music=document.getElementById("music");if(!music)return;const ls=lists();if(ls.length<2)return;const artists=ls[0],albumsList=ls[ls.length-1],disc=music.querySelector(".record-disc");try{const [r,a]=await Promise.all([lastFm("recent"),lastFm("albums")]);const tracks=r?.recenttracks?.track||[],albums=a?.topalbums?.album||[];const current=tracks.find(x=>x?.["@attr"]?.nowplaying==="true")||tracks[0];const songCover=bestImage(current);if(disc&&songCover){disc.style.backgroundImage=`url("${songCover.replace(/"/g,"\\\"")}")`;disc.dataset.artworkLoaded="1"}
[...artists.querySelectorAll(":scope > .music-item")].forEach(item=>{const name=item.querySelector("strong")?.textContent?.trim();if(name)linkItem(item,artistUrl(name))});
[...albumsList.querySelectorAll(":scope > .music-item")].forEach((item,i)=>{const album=albums[i];if(!album)return;const cover=bestImage(album);if(cover){let img=item.querySelector("img.music-album-art");if(!img){img=document.createElement("img");img.className="music-album-art";const content=item.querySelector(":scope > div");if(content)item.insertBefore(img,content);else item.appendChild(img)}img.src=cover;img.alt=`${album.name||"Album"} album cover`;img.loading="eager"}const name=album.name||item.querySelector("strong")?.textContent?.trim()||"",artist=album.artist?.name||item.querySelector("small")?.textContent?.trim()||"";if(name&&artist)linkItem(item,albumUrl(artist,name))});
}catch(e){console.warn("Music artwork load failed",e)}}
function start(){addMusicArtworkStyles();let tries=0;const run=()=>{if(document.getElementById("music"))rebuildMusic();if(++tries>=8)clearInterval(timer)};run();const timer=setInterval(run,1000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
