const MAX_VERSTAPPEN_LOGO="/images/max-verstappen.png";
const FERRARI_LOGO="/images/ferrari.png";
function addSafeStyles(){if(document.getElementById("draven-safe-enhancement-styles"))return;const s=document.createElement("style");s.id="draven-safe-enhancement-styles";s.textContent=`
.f1-points .bar{background:#1b1b20!important;position:relative;border-radius:999px!important;overflow:visible}.f1-points .bar>span{background:#777!important;border-radius:999px!important}.f1-points .bar::before{content:"F1 season completion";position:absolute;left:0;top:calc(100% + 8px);white-space:nowrap;font-size:8px;font-weight:600;letter-spacing:.04em;color:#8f8f98!important;pointer-events:none;background:transparent!important;text-shadow:none!important;box-shadow:none!important}
.f1-points,.next-race{background:#0d0d10!important;border-color:#24242a!important;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.f1-points:hover,.next-race:hover{transform:translateY(-3px);border-color:#3a3a42!important;box-shadow:0 12px 28px #0008,0 0 20px rgba(128,72,190,.22)!important}
.f1-hero{background:linear-gradient(145deg,#101014,#0b0b0e)!important;box-shadow:0 24px 70px #0008!important}.f1-mark{color:#9a9aa2!important}.f1-logo{color:#aaa!important;opacity:.08!important}.interest{background:#0d0d10!important;border-color:#24242a!important}.f1-asset{width:42px;height:42px;object-fit:contain;display:block}.driver-number-logo{width:48px;height:48px;object-fit:contain;display:block;filter:drop-shadow(0 2px 8px #0008)}
.music-item{cursor:pointer}.music-item:hover strong{color:#fff}
@media(max-width:700px){.f1-points .bar::before{font-size:7px}}
`;
document.head.appendChild(s)}
function fixF1Images(){document.querySelectorAll(".interest-image").forEach(img=>{const alt=(img.alt||"").toLowerCase(),src=(img.src||"").toLowerCase();if(alt.includes("max verstappen")||src.includes("seeklogo")||src.includes("liquipedia.net")){img.src=MAX_VERSTAPPEN_LOGO;img.alt="Max Verstappen";img.classList.add("driver-number-logo")}else if(alt.includes("ferrari")||src.includes("scuderia-logo-v02")||src.includes("ferrarioffortlauderdale")){img.src=FERRARI_LOGO;img.alt="Scuderia Ferrari HP";img.classList.add("f1-asset")}})}
function bindMusicLinks(){document.querySelectorAll("#music .music-item").forEach(item=>{if(item.dataset.linkBound==="1")return;const strong=item.querySelector("strong"),small=item.querySelector("small");if(!strong)return;const list=item.closest(".music-list"),isAlbum=list===document.querySelector("#music .music-list:last-child"),name=strong.textContent.trim(),artist=small?.textContent.trim()||"";const url=isAlbum&&artist?`https://www.last.fm/music/${encodeURIComponent(artist).replace(/%20/g,"+")}/${encodeURIComponent(name).replace(/%20/g,"+")}`:`https://www.last.fm/music/${encodeURIComponent(name).replace(/%20/g,"+")}`;item.dataset.linkBound="1";item.addEventListener("click",()=>window.open(url,"_blank","noopener,noreferrer"))})}
function runSafeEnhancements(){addSafeStyles();fixF1Images();bindMusicLinks()}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;runSafeEnhancements()})});observer.observe(document.getElementById("root")||document.body,{childList:true,subtree:true});runSafeEnhancements();
